-- tenant_a;
create schema if not exists tenant_a;
create table if not exists tenant_a.Category
(
    id          bigint generated by default as identity,
    name        varchar(255) not null,
    description varchar(255),
    primary key (id)
);

create table if not exists tenant_a.Product
(
    id             bigint generated by default as identity,
    code           varchar(255)   not null unique,
    name           varchar(255)   not null,
    price          numeric(38, 2) not null,
    description    varchar(255),
    fk_category_id bigint         not null references tenant_a.Category,
    primary key (id)
);

-- tenant_b;
create schema if not exists tenant_b;
create table if not exists tenant_b.Category
(
    id          bigint generated by default as identity,
    name        varchar(255) not null,
    description varchar(255),
    primary key (id)
);

create table if not exists tenant_b.Product
(
    id             bigint generated by default as identity,
    code           varchar(255)   not null unique,
    name           varchar(255)   not null,
    price          numeric(38, 2) not null,
    description    varchar(255),
    fk_category_id bigint         not null references tenant_b.Category,
    primary key (id)
);